In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows")

print("Path to dataset files:", path)

d:\projects\imdb\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\anish\.cache\kagglehub\datasets\harshitshankhdhar\imdb-dataset-of-top-1000-movies-and-tv-shows\1.archive...

100%|██████████| 175k/175k [00:00<00:00, 221kB/s]

Extracting files...
Path to dataset files: C:\Users\anish\.cache\kagglehub\datasets\harshitshankhdhar\imdb-dataset-of-top-1000-movies-and-tv-shows\versions\1

In [2]:
import pandas as pd

In [152]:
movies = pd.read_csv("imdb_top_1000.csv")

In [117]:
movies.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [153]:
movies = movies.rename(columns = {"IMDB_Rating":"imdb"})

In [154]:
movies["Star1"] = movies["Star1"].apply(lambda x: x.split(","))
movies["Star2"] = movies["Star2"].apply(lambda x: x.split(","))
movies["Star3"] = movies["Star3"].apply(lambda x: x.split(","))
movies["Star4"] = movies["Star4"].apply(lambda x: x.split(","))

In [155]:
movies = movies.rename(columns = {"Series_Title":"title"})
movies = movies.rename(columns = {"Released_Year":"year"})
movies = movies.rename(columns = {"Genre":"genre"})
movies["cast"] = movies["Star1"]+ movies["Star2"] + movies["Star3"] + movies["Star4"]

In [121]:
movies.head()

,Poster_Link,title,year,Certificate,Runtime,genre,imdb,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,cast
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,[Tim Robbins],[Morgan Freeman],[Bob Gunton],[William Sadler],2343110,"28,341,469","[Tim Robbins, Morgan Freeman, Bob Gunton, Will..."
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,[Marlon Brando],[Al Pacino],[James Caan],[Diane Keaton],1620367,"134,966,411","[Marlon Brando, Al Pacino, James Caan, Diane K..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,[Christian Bale],[Heath Ledger],[Aaron Eckhart],[Michael Caine],2303232,"534,858,444","[Christian Bale, Heath Ledger, Aaron Eckhart, ..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,[Al Pacino],[Robert De Niro],[Robert Duvall],[Diane Keaton],1129952,"57,300,000","[Al Pacino, Robert De Niro, Robert Duvall, Dia..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,[Henry Fonda],[Lee J. Cobb],[Martin Balsam],[John Fiedler],689845,"4,360,000","[Henry Fonda, Lee J. Cobb, Martin Balsam, John..."

In [165]:
movies.dropna(inplace=True)

In [166]:
movies.shape

(1000, 5)

In [157]:
def remove_space(word):
    l= []
    for i in word:
        l.append(i.replace(" ",""))
    return l

In [158]:
movies['Overview'] = movies['Overview'].apply(lambda x: x.split())

In [159]:
movies['Overview'].iloc[0]

['Two',
 'imprisoned',
 'men',
 'bond',
 'over',
 'a',
 'number',
 'of',
 'years,',
 'finding',
 'solace',
 'and',
 'eventual',
 'redemption',
 'through',
 'acts',
 'of',
 'common',
 'decency.']

In [160]:
movies.head()

,Poster_Link,title,year,Certificate,Runtime,genre,imdb,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,cast
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,"[Two, imprisoned, men, bond, over, a, number, ...",80.0,Frank Darabont,[Tim Robbins],[Morgan Freeman],[Bob Gunton],[William Sadler],2343110,"28,341,469","[Tim Robbins, Morgan Freeman, Bob Gunton, Will..."
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,"[An, organized, crime, dynasty's, aging, patri...",100.0,Francis Ford Coppola,[Marlon Brando],[Al Pacino],[James Caan],[Diane Keaton],1620367,"134,966,411","[Marlon Brando, Al Pacino, James Caan, Diane K..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,"[When, the, menace, known, as, the, Joker, wre...",84.0,Christopher Nolan,[Christian Bale],[Heath Ledger],[Aaron Eckhart],[Michael Caine],2303232,"534,858,444","[Christian Bale, Heath Ledger, Aaron Eckhart, ..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,"[The, early, life, and, career, of, Vito, Corl...",90.0,Francis Ford Coppola,[Al Pacino],[Robert De Niro],[Robert Duvall],[Diane Keaton],1129952,"57,300,000","[Al Pacino, Robert De Niro, Robert Duvall, Dia..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,"[A, jury, holdout, attempts, to, prevent, a, m...",96.0,Sidney Lumet,[Henry Fonda],[Lee J. Cobb],[Martin Balsam],[John Fiedler],689845,"4,360,000","[Henry Fonda, Lee J. Cobb, Martin Balsam, John..."

In [161]:
movies = movies[["title","Overview","genre","Director","cast"]]

In [162]:
movies.head()

,title,Overview,genre,Director,cast
0,The Shawshank Redemption,"[Two, imprisoned, men, bond, over, a, number, ...",Drama,Frank Darabont,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will..."
1,The Godfather,"[An, organized, crime, dynasty's, aging, patri...","Crime, Drama",Francis Ford Coppola,"[Marlon Brando, Al Pacino, James Caan, Diane K..."
2,The Dark Knight,"[When, the, menace, known, as, the, Joker, wre...","Action, Crime, Drama",Christopher Nolan,"[Christian Bale, Heath Ledger, Aaron Eckhart, ..."
3,The Godfather: Part II,"[The, early, life, and, career, of, Vito, Corl...","Crime, Drama",Francis Ford Coppola,"[Al Pacino, Robert De Niro, Robert Duvall, Dia..."
4,12 Angry Men,"[A, jury, holdout, attempts, to, prevent, a, m...","Crime, Drama",Sidney Lumet,"[Henry Fonda, Lee J. Cobb, Martin Balsam, John..."

In [163]:
movies['genre'] = movies['genre'].apply(lambda x: x.split(","))

In [164]:
movies.head()

,title,Overview,genre,Director,cast
0,The Shawshank Redemption,"[Two, imprisoned, men, bond, over, a, number, ...",[Drama],Frank Darabont,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will..."
1,The Godfather,"[An, organized, crime, dynasty's, aging, patri...","[Crime, Drama]",Francis Ford Coppola,"[Marlon Brando, Al Pacino, James Caan, Diane K..."
2,The Dark Knight,"[When, the, menace, known, as, the, Joker, wre...","[Action, Crime, Drama]",Christopher Nolan,"[Christian Bale, Heath Ledger, Aaron Eckhart, ..."
3,The Godfather: Part II,"[The, early, life, and, career, of, Vito, Corl...","[Crime, Drama]",Francis Ford Coppola,"[Al Pacino, Robert De Niro, Robert Duvall, Dia..."
4,12 Angry Men,"[A, jury, holdout, attempts, to, prevent, a, m...","[Crime, Drama]",Sidney Lumet,"[Henry Fonda, Lee J. Cobb, Martin Balsam, John..."

In [167]:
movies['Director'] = movies['Director'].apply(lambda x: x.split(','))

In [168]:
movies.head()

,title,Overview,genre,Director,cast
0,The Shawshank Redemption,"[Two, imprisoned, men, bond, over, a, number, ...",[Drama],[Frank Darabont],"[Tim Robbins, Morgan Freeman, Bob Gunton, Will..."
1,The Godfather,"[An, organized, crime, dynasty's, aging, patri...","[Crime, Drama]",[Francis Ford Coppola],"[Marlon Brando, Al Pacino, James Caan, Diane K..."
2,The Dark Knight,"[When, the, menace, known, as, the, Joker, wre...","[Action, Crime, Drama]",[Christopher Nolan],"[Christian Bale, Heath Ledger, Aaron Eckhart, ..."
3,The Godfather: Part II,"[The, early, life, and, career, of, Vito, Corl...","[Crime, Drama]",[Francis Ford Coppola],"[Al Pacino, Robert De Niro, Robert Duvall, Dia..."
4,12 Angry Men,"[A, jury, holdout, attempts, to, prevent, a, m...","[Crime, Drama]",[Sidney Lumet],"[Henry Fonda, Lee J. Cobb, Martin Balsam, John..."

In [169]:

movies["Director"] = movies["Director"].apply(remove_space)
movies["cast"] = movies["cast"].apply(remove_space)

In [170]:
movies.head()

,title,Overview,genre,Director,cast
0,The Shawshank Redemption,"[Two, imprisoned, men, bond, over, a, number, ...",[Drama],[FrankDarabont],"[TimRobbins, MorganFreeman, BobGunton, William..."
1,The Godfather,"[An, organized, crime, dynasty's, aging, patri...","[Crime, Drama]",[FrancisFordCoppola],"[MarlonBrando, AlPacino, JamesCaan, DianeKeaton]"
2,The Dark Knight,"[When, the, menace, known, as, the, Joker, wre...","[Action, Crime, Drama]",[ChristopherNolan],"[ChristianBale, HeathLedger, AaronEckhart, Mic..."
3,The Godfather: Part II,"[The, early, life, and, career, of, Vito, Corl...","[Crime, Drama]",[FrancisFordCoppola],"[AlPacino, RobertDeNiro, RobertDuvall, DianeKe..."
4,12 Angry Men,"[A, jury, holdout, attempts, to, prevent, a, m...","[Crime, Drama]",[SidneyLumet],"[HenryFonda, LeeJ.Cobb, MartinBalsam, JohnFied..."

In [171]:
movies["cast"].iloc[0]

['TimRobbins', 'MorganFreeman', 'BobGunton', 'WilliamSadler']

In [172]:
movies["tags"] = movies["Overview"] + movies["genre"] + movies["Director"] + movies["cast"]

In [173]:
movies.head(1)

,title,Overview,genre,Director,cast,tags
0,The Shawshank Redemption,"[Two, imprisoned, men, bond, over, a, number, ...",[Drama],[FrankDarabont],"[TimRobbins, MorganFreeman, BobGunton, William...","[Two, imprisoned, men, bond, over, a, number, ..."

In [174]:
movies = movies[['title','tags']]

In [175]:
movies.head()

                      title                                               tags
0  The Shawshank Redemption  [Two, imprisoned, men, bond, over, a, number, ...
1             The Godfather  [An, organized, crime, dynasty's, aging, patri...
2           The Dark Knight  [When, the, menace, known, as, the, Joker, wre...
3    The Godfather: Part II  [The, early, life, and, career, of, Vito, Corl...
4              12 Angry Men  [A, jury, holdout, attempts, to, prevent, a, m...

In [176]:
from nltk.stem import PorterStemmer
ps  = PorterStemmer()
def stems(text):
    l = []
    for i in text.split():
        l.append(ps.stem(i))
    return " ".join(l)

In [177]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [178]:
movies['tags'] = movies['tags'].apply(lambda x: x.lower())

In [179]:
movies.head(1)

                      title                                               tags
0  The Shawshank Redemption  two imprisoned men bond over a number of years...

In [180]:
movies['tags'] = movies['tags'].apply(stems)

In [181]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [182]:
cv = CountVectorizer(max_features=5000, stop_words='english')

vector = cv.fit_transform(movies['tags']).toarray()

In [183]:
similarity = cosine_similarity(vector)

In [184]:
similarity

array([[1.        , 0.05572782, 0.05345225, ..., 0.05455447, 0.05832118,
        0.        ],
       [0.05572782, 1.        , 0.20851441, ..., 0.21281413, 0.04550158,
        0.0725954 ],
       [0.05345225, 0.20851441, 1.        , ..., 0.12247449, 0.04364358,
        0.03481553],
       ...,
       [0.05455447, 0.21281413, 0.12247449, ..., 1.        , 0.13363062,
        0.        ],
       [0.05832118, 0.04550158, 0.04364358, ..., 0.13363062, 1.        ,
        0.03798686],
       [0.        , 0.0725954 , 0.03481553, ..., 0.        , 0.03798686,
        1.        ]], shape=(1000, 1000))

In [185]:
def recommend(movie):

    index = movies[movies['title'] == movie].index[0]

    distance = sorted(
        list(enumerate(similarity[index])),
        reverse=True,
        key=lambda x: x[1]
    )

    for i in distance[1:6]:
        print(movies.iloc[i[0]].title)

In [186]:
recommend("The Shawshank Redemption")

Mystic River
Oldeuboi
Fa yeung nin wah
La Grande Illusion
Eskiya

In [187]:
recommend("The Dark Knight")

Batman Begins
The Dark Knight Rises
The Godfather: Part III
Dip huet seung hung
Scarface: The Shame of the Nation

In [192]:
recommend("The Godfather: Part III")

The Godfather: Part II
The Godfather
Goodfellas
Fargo
Haider